#!/bin/bash
# =============================================================================
# AgentsMesh 开发环境一键初始化脚本
# =============================================================================
#
# 一键启动完整的开发环境，包括：
#   1. 生成 worktree 隔离的 .env 配置
#   2. 启动后端 Docker 服务（前端在本地运行）
#   3. 执行数据库迁移
#   4. 初始化 seed 数据
#
# 使用方法：
#   ./dev.sh         # 一键启动开发环境
#   ./dev.sh --clean # 清理并重建（失败时使用）
#
# 本地前端开发：
#   cd web && pnpm dev --turbopack
#
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
MIGRATIONS_DIR="$SCRIPT_DIR/../../backend/migrations"
SEED_FILE="$SCRIPT_DIR/seed/seed.sql"
LEMONSQUEEZY_SEED_FILE="$SCRIPT_DIR/seed/seed_lemonsqueezy.sql"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

# 获取 worktree 名称
get_worktree_name() {
    local git_dir
    git_dir=$(git rev-parse --git-dir 2>/dev/null)

    if [[ "$git_dir" == *".git/worktrees/"* ]]; then
        # worktree 的 git-dir 格式: /path/to/repo/.git/worktrees/<worktree-name>
        basename "$git_dir"
    else
        git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main"
    fi | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]'
}

# 计算端口偏移量
# 使用 6 位哈希，范围 1-500，降低冲突概率
calculate_port_offset() {
    local name="$1"
    if [[ "$name" == "main" || "$name" == "master" ]]; then
        echo 0
    else
        local hash
        if command -v md5sum &>/dev/null; then
            hash=$(echo -n "$name" | md5sum | cut -c1-6)
        else
            hash=$(echo -n "$name" | md5 | cut -c1-6)
        fi
        echo $(( (16#$hash % 500) + 1 ))
    fi
}

# 生成 SSL 证书 (gRPC + mTLS)
generate_ssl_certs() {
    local ssl_dir="$SCRIPT_DIR/ssl"
    if [ -f "$ssl_dir/ca.crt" ] && [ -f "$ssl_dir/ca.key" ]; then
        info "SSL 证书已存在"
        return 0
    fi

    info "生成 SSL 证书 (gRPC + mTLS)..."
    "$SCRIPT_DIR/generate-dev-certs.sh" > /dev/null 2>&1
    success "SSL 证书生成完成"
}

# 生成 AI CLI 配置文件
generate_ai_cli_configs() {
    local config_dir="$SCRIPT_DIR/ai-cli-configs"

    # Claude Code settings
    mkdir -p "$config_dir/claude"
    cat > "$config_dir/claude/settings.json" << 'EOF'
{
  "permissions": {
    "allow": [
      "Bash",
      "Read",
      "Write",
      "Edit",
      "Glob",
      "Grep"
    ],
    "deny": []
  },
  "api_key_helper": null
}
EOF

    # Codex CLI config
    mkdir -p "$config_dir/codex"
    cat > "$config_dir/codex/config.toml" << 'EOF'
# Codex CLI configuration for headless mode

[defaults]
# Allow full auto mode for non-interactive execution
approval_mode = "full-auto"
EOF

    # Gemini CLI settings
    mkdir -p "$config_dir/gemini"
    cat > "$config_dir/gemini/settings.json" << 'EOF'
{
  "sandboxMode": "none",
  "autoApprove": true
}
EOF

    success "生成 AI CLI 配置"
}

# 生成 Traefik 配置（动态设置网络名）
generate_traefik_config() {
    local worktree_name="${WORKTREE_NAME:-main}"
    local project_name="agentsmesh-${worktree_name}"
    local network_name="${project_name}_default"
    local traefik_yml="$SCRIPT_DIR/traefik/traefik.yml"

    cat > "$traefik_yml" << EOF
# Traefik Static Configuration for Development
# Auto-generated by dev.sh - project: $project_name

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  grpc:
    address: ":9443"

providers:
  docker:
    exposedByDefault: false
    network: $network_name
    # Only discover containers with this project's label
    constraints: "Label(\`com.docker.compose.project\`, \`$project_name\`)"
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: DEBUG
  format: common

accessLog:
  format: common
EOF
    success "生成 Traefik 配置 (network: $network_name)"
}

# 生成 .env 配置
generate_env() {
    local worktree_name=$(get_worktree_name)
    local offset=$(calculate_port_offset "$worktree_name")
    local project_name="agentsmesh-${worktree_name}"

    # 保存到全局变量供其他函数使用
    WORKTREE_NAME="$worktree_name"
    PORT_OFFSET="$offset"

    # 计算端口
    local http_port=$((10000 + offset * 50))
    local grpc_port=$((10001 + offset * 50))

    cat > "$ENV_FILE" << EOF
# AgentsMesh Dev Environment - Auto-generated
# Worktree: $worktree_name | Offset: $offset

COMPOSE_PROJECT_NAME=$project_name

# =============================================================================
# Unified Domain Configuration - Single Source of Truth
# All URLs (OAuth callbacks, webhooks, Relay, etc.) are derived from this
# =============================================================================
PRIMARY_DOMAIN=localhost:$http_port
USE_HTTPS=false

# =============================================================================
# Ports (步长 50，支持最多 500 个 worktree，端口范围 10000-35000)
# =============================================================================
HTTP_PORT=$http_port
GRPC_PORT=$grpc_port
POSTGRES_PORT=$((10002 + offset * 50))
REDIS_PORT=$((10003 + offset * 50))
MINIO_API_PORT=$((10004 + offset * 50))
MINIO_CONSOLE_PORT=$((10005 + offset * 50))
ADMINER_PORT=$((10006 + offset * 50))
WEB_PORT=$((10007 + offset * 50))
TRAEFIK_DASHBOARD_PORT=$((10008 + offset * 50))
GITEA_HTTP_PORT=$((10009 + offset * 50))
GITEA_SSH_PORT=$((10010 + offset * 50))

# =============================================================================
# Credentials
# =============================================================================
POSTGRES_PASSWORD=agentsmesh_dev
JWT_SECRET=dev-jwt-secret-change-in-production
INTERNAL_API_SECRET=dev-internal-secret
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin

# =============================================================================
# OAuth (optional) - Only ClientID/Secret needed, RedirectURLs derived
# =============================================================================
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=

# =============================================================================
# AI CLI - Claude Code
# =============================================================================
ANTHROPIC_BASE_URL=https://api.anthropic.com
ANTHROPIC_AUTH_TOKEN=
EOF
    success "生成 .env 配置 (worktree: $worktree_name, PRIMARY_DOMAIN: localhost:$http_port)"
}

# 生成 web/.env.local 配置（支持本地前端开发）
generate_web_env() {
    local offset="${PORT_OFFSET:-0}"
    local worktree_name="${WORKTREE_NAME:-main}"
    local http_port=$((10000 + offset * 50))
    local web_env_file="$SCRIPT_DIR/../../web/.env.local"

    cat > "$web_env_file" << EOF
# Auto-generated by dev.sh
# Worktree: $worktree_name | HTTP Port: $http_port
#
# Unified Domain Configuration - 所有 URL 从 PRIMARY_DOMAIN 派生
# 变量名与 Backend/Relay 完全统一

# =============================================================================
# Unified Domain Configuration - Single Source of Truth
# =============================================================================
PRIMARY_DOMAIN=localhost:$http_port
USE_HTTPS=false

# =============================================================================
# 本地开发特殊配置
# =============================================================================
# 前端 API 基础 URL（留空使用相对路径，由 Next.js rewrites 代理）
NEXT_PUBLIC_API_URL=

# WebSocket URL（直连后端，Next.js rewrites 不支持 WebSocket 代理）
NEXT_PUBLIC_WS_URL=ws://127.0.0.1:$http_port

# Next.js rewrites 代理目标（仅服务端使用，不暴露给浏览器）
# 使用 127.0.0.1 而非 localhost，避免 IPv6 解析问题（Docker 端口映射只绑定 IPv4）
API_PROXY_TARGET=http://127.0.0.1:$http_port

# OAuth (optional)
NEXT_PUBLIC_GITHUB_CLIENT_ID=
EOF
    success "生成 web/.env.local (PRIMARY_DOMAIN: localhost:$http_port)"
}

# 等待服务就绪
wait_for_service() {
    local container="$1"
    local check_cmd="$2"
    local max_retries=30

    for ((i=1; i<=max_retries; i++)); do
        if docker exec "$container" $check_cmd &>/dev/null; then
            return 0
        fi
        sleep 2
    done
    return 1
}

# 执行数据库迁移
run_migrations() {
    local backend_container="${COMPOSE_PROJECT_NAME}-backend-1"
    local db_url="postgres://agentsmesh:agentsmesh_dev@postgres:5432/agentsmesh?sslmode=disable"

    info "检查数据库迁移状态..."

    # 等待 backend 容器就绪（migrate 工具在 backend 容器中）
    local max_wait=30
    for ((i=1; i<=max_wait; i++)); do
        if docker exec "$backend_container" migrate -version &>/dev/null; then
            break
        fi
        sleep 1
    done

    # 检查迁移状态
    local migration_output
    migration_output=$(docker exec "$backend_container" migrate \
        -path /app/migrations \
        -database "$db_url" \
        version 2>&1) || true

    # 检查是否有 dirty 状态
    if echo "$migration_output" | grep -q "dirty"; then
        warn "检测到迁移状态为 dirty，尝试修复..."
        local dirty_version
        dirty_version=$(echo "$migration_output" | grep -oE '[0-9]+' | head -1)
        if [[ -n "$dirty_version" ]]; then
            docker exec "$backend_container" migrate \
                -path /app/migrations \
                -database "$db_url" \
                force "$dirty_version" 2>/dev/null || true
            success "已修复 dirty 状态 (version: $dirty_version)"
        fi
    fi

    # 执行迁移
    info "执行数据库迁移..."
    local migrate_result
    migrate_result=$(docker exec "$backend_container" migrate \
        -path /app/migrations \
        -database "$db_url" \
        up 2>&1) || true

    # 检查迁移结果
    # 注意: 使用 "^error" 匹配行首，避免误匹配迁移文件名中包含 "error" 的条目
    # (如 000046_add_pod_error_fields)
    if echo "$migrate_result" | grep -q "no change"; then
        info "数据库已是最新版本"
    elif echo "$migrate_result" | grep -q "^error"; then
        # 如果迁移失败，可能是部分迁移已手动完成，尝试逐个跳过
        warn "迁移遇到错误，尝试继续..."
        local current_version
        current_version=$(docker exec "$backend_container" migrate \
            -path /app/migrations \
            -database "$db_url" \
            version 2>&1 | grep -oE '^[0-9]+' || echo "0")

        # 获取最新迁移版本
        local latest_version
        latest_version=$(ls -1 "$MIGRATIONS_DIR"/*.up.sql 2>/dev/null | \
            sed 's/.*\/\([0-9]*\)_.*/\1/' | sort -n | tail -1)

        if [[ -n "$latest_version" && "$current_version" != "$latest_version" ]]; then
            # 尝试强制设置到最新版本（仅在开发环境使用）
            warn "跳过失败的迁移，强制设置版本为 $latest_version"
            docker exec "$backend_container" migrate \
                -path /app/migrations \
                -database "$db_url" \
                force "$latest_version" 2>/dev/null || true
        fi
    else
        success "数据库迁移完成"
    fi

    # 显示最终版本
    local final_version
    final_version=$(docker exec "$backend_container" migrate \
        -path /app/migrations \
        -database "$db_url" \
        version 2>&1 | head -1)
    info "当前迁移版本: $final_version"
}

# 初始化 seed 数据
init_seed() {
    local pg_container="$1"

    # 检查是否已有 seed 数据
    local user_exists
    user_exists=$(docker exec "$pg_container" psql -U agentsmesh -d agentsmesh -t -c \
        "SELECT COUNT(*) FROM users WHERE email = 'dev@agentsmesh.local'" 2>/dev/null | tr -d ' ')

    if [[ "$user_exists" -gt 0 ]]; then
        info "Seed 数据已存在，跳过"
        return 0
    fi

    info "初始化 seed 数据..."
    docker exec -i "$pg_container" psql -U agentsmesh -d agentsmesh < "$SEED_FILE" &>/dev/null

    # 应用 LemonSqueezy Variant IDs 配置
    if [[ -f "$LEMONSQUEEZY_SEED_FILE" ]]; then
        info "配置 LemonSqueezy Variant IDs..."
        docker exec -i "$pg_container" psql -U agentsmesh -d agentsmesh < "$LEMONSQUEEZY_SEED_FILE" &>/dev/null
    fi

    success "Seed 数据初始化完成"
}

# 初始化 Gitea Git 服务器
init_gitea() {
    local gitea_container="${COMPOSE_PROJECT_NAME}-gitea-1"
    source "$ENV_FILE"
    local gitea_port="${GITEA_HTTP_PORT:-3001}"

    # Wait for Gitea healthcheck
    info "等待 Gitea 就绪..."
    local max_retries=30
    for ((i=1; i<=max_retries; i++)); do
        if curl -s "http://localhost:${gitea_port}/api/v1/version" &>/dev/null; then
            break
        fi
        if [[ $i -eq $max_retries ]]; then
            warn "Gitea 启动超时，跳过初始化"
            return 0
        fi
        sleep 2
    done
    success "Gitea 已就绪"

    # Run init script
    "$SCRIPT_DIR/gitea/init-gitea.sh" "$gitea_container" "$gitea_port"
}

# 清理环境
clean() {
    # 读取端口配置
    if [[ -f "$ENV_FILE" ]]; then
        source "$ENV_FILE"
    fi
    local web_port="${WEB_PORT:-3000}"

    # 停止前端进程
    if lsof -i :"$web_port" &>/dev/null; then
        info "停止前端服务 (端口: $web_port)..."
        lsof -ti :"$web_port" | xargs kill -9 2>/dev/null || true
        success "前端服务已停止"
    fi

    # 清理前端日志
    rm -f "$SCRIPT_DIR/web.log"

    if [[ -f "$ENV_FILE" ]]; then
        info "清理 Docker 环境: ${COMPOSE_PROJECT_NAME:-agentsmesh}..."
        cd "$SCRIPT_DIR"
        docker compose down -v --remove-orphans 2>/dev/null || true
        rm -f "$ENV_FILE"
        success "清理完成"
    else
        warn "Docker 环境未初始化"
    fi
}

# 显示结果
show_result() {
    source "$ENV_FILE"

    echo ""
    echo "=========================================="
    echo "  AgentsMesh 开发环境已就绪!"
    echo "=========================================="
    echo ""
    echo "  前端:       http://localhost:$WEB_PORT"
    echo "  API:        http://localhost:$HTTP_PORT/api"
    echo "  Relay:      ws://localhost:$HTTP_PORT/relay (via Traefik)"
    echo ""
    echo "  测试账号:   dev@agentsmesh.local / devpass123"
    echo "  管理员:     admin@agentsmesh.local / adminpass123"
    echo ""
    echo "  其他服务:"
    echo "    Gitea:    http://localhost:$GITEA_HTTP_PORT (gitea-admin / gitea-admin-123)"
    echo "    Traefik:  http://localhost:$TRAEFIK_DASHBOARD_PORT (Dashboard)"
    echo "    Adminer:  http://localhost:$ADMINER_PORT"
    echo "    MinIO:    http://localhost:$MINIO_CONSOLE_PORT"
    echo "    gRPC:     grpcs://localhost:$GRPC_PORT (mTLS)"
    echo ""
    echo "  停止: ./dev.sh --clean"
    echo ""
}

# 启动本地前端
start_frontend() {
    source "$ENV_FILE"
    local web_dir="$SCRIPT_DIR/../../web"
    local web_port="${WEB_PORT:-3000}"

    # 检查是否已有前端进程在运行
    if lsof -i :"$web_port" &>/dev/null; then
        warn "端口 $web_port 已被占用，跳过前端启动"
        return 0
    fi

    # 检查 pnpm
    if ! command -v pnpm &>/dev/null; then
        error "未找到 pnpm，请先安装: npm install -g pnpm"
        return 1
    fi

    # 检查依赖
    if [[ ! -d "$web_dir/node_modules" ]]; then
        info "安装前端依赖..."
        (cd "$web_dir" && pnpm install --frozen-lockfile) || {
            error "前端依赖安装失败"
            return 1
        }
        success "前端依赖安装完成"
    fi

    # 启动前端（后台运行，日志输出到文件）
    local log_file="$SCRIPT_DIR/web.log"
    info "启动前端服务 (端口: $web_port)..."
    (cd "$web_dir" && nohup pnpm dev --turbopack --port "$web_port" > "$log_file" 2>&1 &)

    # 等待前端启动
    local max_wait=30
    for ((i=1; i<=max_wait; i++)); do
        if curl -s "http://localhost:$web_port" &>/dev/null; then
            success "前端服务已启动 (http://localhost:$web_port)"
            return 0
        fi
        sleep 1
    done

    warn "前端服务启动中，请稍后访问 http://localhost:$web_port"
    echo "  查看日志: tail -f $log_file"
}

# 主流程
main() {
    cd "$SCRIPT_DIR"

    # 处理 --clean 参数
    if [[ "${1:-}" == "--clean" || "${1:-}" == "-c" ]]; then
        clean
        exit 0
    fi

    # 显示帮助
    if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
        echo "用法: $0 [选项]"
        echo ""
        echo "选项:"
        echo "  无参数    一键启动完整开发环境（Docker 后端 + 本地前端）"
        echo "  --clean   停止并清理所有服务"
        echo ""
        echo "前端日志: tail -f deploy/dev/web.log"
        exit 0
    fi

    echo ""
    echo "=========================================="
    echo "  AgentsMesh 开发环境初始化"
    echo "=========================================="
    echo ""

    # Step 1: 生成 SSL 证书
    generate_ssl_certs

    # Step 2: 生成 AI CLI 配置
    generate_ai_cli_configs

    # Step 3: 生成配置
    generate_env
    source "$ENV_FILE"

    # Step 4: 生成 Traefik 配置（动态网络名，解决多 worktree 路由冲突）
    generate_traefik_config

    # Step 5: 生成 web/.env.local（支持本地前端开发）
    generate_web_env

    # Step 6: 启动 Docker 后端服务
    info "启动 Docker 服务 (首次可能需要几分钟)..."
    docker compose up -d --build --quiet-pull 2>&1 | grep -v "^#" | grep -v "^\[" | grep -v "^$" || true
    success "Docker 服务已启动"

    # Step 7: 等待 PostgreSQL
    local pg_container="${COMPOSE_PROJECT_NAME}-postgres-1"
    info "等待 PostgreSQL 就绪..."
    if ! wait_for_service "$pg_container" "pg_isready -U agentsmesh"; then
        error "PostgreSQL 启动超时"
        exit 1
    fi
    success "PostgreSQL 已就绪"

    # Step 8: 执行迁移（使用 backend 容器中的 migrate 工具）
    run_migrations

    # Step 9: 初始化 seed
    init_seed "$pg_container"

    # Step 9.5: 初始化 Gitea Git 服务器
    init_gitea

    # Step 10: 修复 workspace 权限 (runner 容器)
    local runner_container="${COMPOSE_PROJECT_NAME}-runner-1"
    docker exec -u root "$runner_container" chown -R runner:runner /workspace 2>/dev/null || true

    # Step 11: 启动本地前端
    start_frontend

    # 显示结果
    show_result
}

main "$@"
