// Package client provides gRPC registration for Runner.
package client

import (
	"bytes"
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"

	"github.com/pkg/browser"
)

// ==================== Tailscale-style Interactive Registration ====================

// InteractiveRegistrationRequest contains parameters for interactive registration.
type InteractiveRegistrationRequest struct {
	ServerURL  string            // Base server URL (e.g., https://app.example.com)
	MachineKey string            // Unique machine key generated by Runner
	NodeID     string            // Optional node ID (hostname if empty)
	Labels     map[string]string // Optional labels
}

// InteractiveRegistrationResult contains the result of interactive registration.
type InteractiveRegistrationResult struct {
	RunnerID      int64  `json:"runner_id"`
	Certificate   string `json:"certificate"`
	PrivateKey    string `json:"private_key"`
	CACertificate string `json:"ca_certificate"`
	GRPCEndpoint  string `json:"grpc_endpoint"`
	OrgSlug       string `json:"org_slug"`
}

// RequestAuthURL requests an authorization URL from the server.
// Step 1 of interactive registration - Runner requests auth URL.
func RequestAuthURL(ctx context.Context, req InteractiveRegistrationRequest) (authURL, authKey string, expiresIn int, err error) {
	requestURL := fmt.Sprintf("%s/api/v1/runners/grpc/auth-url", req.ServerURL)

	body := map[string]interface{}{
		"machine_key": req.MachineKey,
	}
	if req.NodeID != "" {
		body["node_id"] = req.NodeID
	}
	if len(req.Labels) > 0 {
		body["labels"] = req.Labels
	}

	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return "", "", 0, fmt.Errorf("failed to marshal request body: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, bytes.NewReader(bodyBytes))
	if err != nil {
		return "", "", 0, fmt.Errorf("failed to create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(httpReq)
	if err != nil {
		return "", "", 0, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return "", "", 0, fmt.Errorf("server returned status %d: %s", resp.StatusCode, string(respBody))
	}

	var result struct {
		AuthURL   string `json:"auth_url"`
		AuthKey   string `json:"auth_key"`
		ExpiresIn int    `json:"expires_in"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", "", 0, fmt.Errorf("failed to decode response: %w", err)
	}

	return result.AuthURL, result.AuthKey, result.ExpiresIn, nil
}

// AuthStatus represents the status of a pending authorization.
type AuthStatus struct {
	Status        string `json:"status"` // "pending", "authorized"
	RunnerID      int64  `json:"runner_id,omitempty"`
	Certificate   string `json:"certificate,omitempty"`
	PrivateKey    string `json:"private_key,omitempty"`
	CACertificate string `json:"ca_certificate,omitempty"`
	GRPCEndpoint  string `json:"grpc_endpoint,omitempty"`
	OrgSlug       string `json:"org_slug,omitempty"`
}

// GetAuthStatus polls the server for authorization status.
// Step 2 of interactive registration - Runner polls until authorized.
func GetAuthStatus(ctx context.Context, serverURL, authKey string) (*AuthStatus, error) {
	requestURL := fmt.Sprintf("%s/api/v1/runners/grpc/auth-status?key=%s", serverURL, authKey)

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusNotFound {
		return nil, fmt.Errorf("authorization request not found or expired")
	}

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("server returned status %d: %s", resp.StatusCode, string(respBody))
	}

	var status AuthStatus
	if err := json.NewDecoder(resp.Body).Decode(&status); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &status, nil
}

// InteractiveRegister performs Tailscale-style interactive registration.
// Opens a browser for user authorization and polls for completion.
func InteractiveRegister(ctx context.Context, req InteractiveRegistrationRequest) (*InteractiveRegistrationResult, error) {
	// Step 1: Request auth URL
	authURL, authKey, expiresIn, err := RequestAuthURL(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to request auth URL: %w", err)
	}

	fmt.Printf("\nPlease open this link in your browser to authorize:\n\n  %s\n\n", authURL)
	fmt.Printf("The authorization link will expire in %d seconds\n\n", expiresIn)

	// Try to open browser
	if err := browser.OpenURL(authURL); err != nil {
		fmt.Printf("Unable to open browser automatically, please copy the link manually\n")
	}

	// Step 2: Poll for authorization status
	fmt.Print("Waiting for authorization")
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	timeout := time.After(time.Duration(expiresIn) * time.Second)

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-timeout:
			return nil, fmt.Errorf("authorization timeout after %d seconds", expiresIn)
		case <-ticker.C:
			fmt.Print(".")

			status, err := GetAuthStatus(ctx, req.ServerURL, authKey)
			if err != nil {
				// Log error but continue polling
				continue
			}

			if status.Status == "authorized" {
				fmt.Println("\n\n✅ Authorization successful!")
				return &InteractiveRegistrationResult{
					RunnerID:      status.RunnerID,
					Certificate:   status.Certificate,
					PrivateKey:    status.PrivateKey,
					CACertificate: status.CACertificate,
					GRPCEndpoint:  status.GRPCEndpoint,
					OrgSlug:       status.OrgSlug,
				}, nil
			}
		}
	}
}

// ==================== Pre-generated Token Registration ====================

// TokenRegistrationRequest contains parameters for token-based registration.
type TokenRegistrationRequest struct {
	ServerURL string // Base server URL
	Token     string // Pre-generated registration token
	NodeID    string // Optional node ID
}

// TokenRegistrationResult contains the result of token-based registration.
type TokenRegistrationResult struct {
	RunnerID      int64  `json:"runner_id"`
	Certificate   string `json:"certificate"`
	PrivateKey    string `json:"private_key"`
	CACertificate string `json:"ca_certificate"`
	GRPCEndpoint  string `json:"grpc_endpoint"`
	OrgSlug       string `json:"org_slug"`
}

// RegisterWithToken registers a runner using a pre-generated token.
// Direct registration without browser authorization.
func RegisterWithToken(ctx context.Context, req TokenRegistrationRequest) (*TokenRegistrationResult, error) {
	requestURL := fmt.Sprintf("%s/api/v1/runners/grpc/register", req.ServerURL)

	body := map[string]interface{}{
		"token": req.Token,
	}
	if req.NodeID != "" {
		body["node_id"] = req.NodeID
	}

	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request body: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusUnauthorized {
		return nil, fmt.Errorf("invalid or expired token")
	}
	if resp.StatusCode == http.StatusConflict {
		return nil, fmt.Errorf("runner with this node_id already exists")
	}
	if resp.StatusCode == http.StatusPaymentRequired {
		return nil, fmt.Errorf("runner quota exceeded")
	}
	if resp.StatusCode != http.StatusCreated {
		respBody, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("server returned status %d: %s", resp.StatusCode, string(respBody))
	}

	var result TokenRegistrationResult
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	if result.Certificate == "" {
		return nil, fmt.Errorf("server returned empty certificate")
	}

	return &result, nil
}

// ==================== Certificate Reactivation ====================

// ReactivationRequest contains parameters for reactivating an expired runner.
type ReactivationRequest struct {
	ServerURL string // Base server URL
	Token     string // One-time reactivation token
}

// ReactivationResult contains the result of reactivation.
type ReactivationResult struct {
	Certificate   string `json:"certificate"`
	PrivateKey    string `json:"private_key"`
	CACertificate string `json:"ca_certificate"`
	GRPCEndpoint  string `json:"grpc_endpoint"`
}

// Reactivate reactivates a runner with an expired certificate using a one-time token.
func Reactivate(ctx context.Context, req ReactivationRequest) (*ReactivationResult, error) {
	requestURL := fmt.Sprintf("%s/api/v1/runners/grpc/reactivate", req.ServerURL)

	body := map[string]interface{}{
		"token": req.Token,
	}

	bodyBytes, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request body: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusUnauthorized {
		return nil, fmt.Errorf("invalid or expired reactivation token")
	}
	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("server returned status %d: %s", resp.StatusCode, string(respBody))
	}

	var result ReactivationResult
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &result, nil
}

// ==================== Certificate Renewal ====================

// RenewalRequest contains parameters for certificate renewal.
type RenewalRequest struct {
	ServerURL string // Base server URL
	CertFile  string // Path to current client certificate
	KeyFile   string // Path to current client private key
	CAFile    string // Path to CA certificate
}

// RenewalResult contains the result of certificate renewal.
type RenewalResult struct {
	Certificate string `json:"certificate"`
	PrivateKey  string `json:"private_key"`
	ExpiresAt   int64  `json:"expires_at"`
}

// RenewCertificate renews the runner's certificate using mTLS authentication.
// Note: This requires a valid (not expired) certificate for mTLS.
func RenewCertificate(ctx context.Context, req RenewalRequest) (*RenewalResult, error) {
	// Load client certificate for mTLS
	cert, err := tls.LoadX509KeyPair(req.CertFile, req.KeyFile)
	if err != nil {
		return nil, fmt.Errorf("failed to load client certificate: %w", err)
	}

	// Load CA certificate (only trust AgentMesh CA)
	caCert, err := os.ReadFile(req.CAFile)
	if err != nil {
		return nil, fmt.Errorf("failed to read CA certificate: %w", err)
	}

	caPool := x509.NewCertPool()
	if !caPool.AppendCertsFromPEM(caCert) {
		return nil, fmt.Errorf("failed to parse CA certificate")
	}

	// Configure mTLS for HTTP client
	tlsConfig := &tls.Config{
		Certificates: []tls.Certificate{cert},
		RootCAs:      caPool,
		MinVersion:   tls.VersionTLS13,
	}

	client := &http.Client{
		Timeout: 30 * time.Second,
		Transport: &http.Transport{
			TLSClientConfig: tlsConfig,
		},
	}

	requestURL := fmt.Sprintf("%s/api/v1/runners/grpc/renew-certificate", req.ServerURL)

	httpReq, err := http.NewRequestWithContext(ctx, "POST", requestURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	resp, err := client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("server returned status %d: %s", resp.StatusCode, string(respBody))
	}

	var result RenewalResult
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &result, nil
}
